[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCodeNerdFont Mono", style = "regular"}

bold = { family = "FiraCodeNerdFont Mono", style = "bold" }

italic = { family = "FiraCodeNerdFont Mono", style = "medium" }

bold_italic = { family = "FiraCodeNerdFont Mono", style = "semibold"}

size = 11

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
